# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'our_plugin_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OurPluginDialogBase(object):
    def setupUi(self, OurPluginDialogBase):
        OurPluginDialogBase.setObjectName("OurPluginDialogBase")
        OurPluginDialogBase.resize(495, 367)
        self.button_box = QtWidgets.QDialogButtonBox(OurPluginDialogBase)
        self.button_box.setGeometry(QtCore.QRect(140, 330, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label = QtWidgets.QLabel(OurPluginDialogBase)
        self.label.setGeometry(QtCore.QRect(90, 40, 201, 31))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(OurPluginDialogBase)
        self.pushButton.setGeometry(QtCore.QRect(330, 290, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.mComboBox = QgsCheckableComboBox(OurPluginDialogBase)
        self.mComboBox.setGeometry(QtCore.QRect(70, 90, 160, 27))
        self.mComboBox.setObjectName("mComboBox")
        self.listWidget = QtWidgets.QListWidget(OurPluginDialogBase)
        self.listWidget.setGeometry(QtCore.QRect(70, 230, 141, 81))
        self.listWidget.setObjectName("listWidget")
        self.mLineEdit = QgsFilterLineEdit(OurPluginDialogBase)
        self.mLineEdit.setGeometry(QtCore.QRect(310, 50, 60, 27))
        self.mLineEdit.setProperty("qgisRelation", "")
        self.mLineEdit.setObjectName("mLineEdit")
        self.graphicsView = QtWidgets.QGraphicsView(OurPluginDialogBase)
        self.graphicsView.setGeometry(QtCore.QRect(70, 150, 61, 41))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(OurPluginDialogBase)
        self.button_box.accepted.connect(OurPluginDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(OurPluginDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OurPluginDialogBase)

    def retranslateUi(self, OurPluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        OurPluginDialogBase.setWindowTitle(_translate("OurPluginDialogBase", "Our Plugin"))
        self.label.setText(_translate("OurPluginDialogBase", "Różnica wysokości między punktami:"))
        self.pushButton.setText(_translate("OurPluginDialogBase", "Oblicz"))
from qgscheckablecombobox import QgsCheckableComboBox
from qgsfilterlineedit import QgsFilterLineEdit
